name: tranquil_life
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

###
### Please arrange packages alphabetically to make it easier to find them later on
###
dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  flutter_native_splash: ^2.2.7
  flutter_staggered_grid_view: ^0.6.2
  flutter_speed_dial: ^6.0.0
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  intl_phone_field: ^3.1.0
  json_annotation: ^4.6.0
  photo_view: ^0.14.0
  #local_auth: ^2.1.1

  # flutter_switch: ^0.3.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  json_serializable: ^6.3.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/onboarding/

  fonts:
    - family: Tranquil
      fonts:
        - asset: fonts/Tranquil.ttf

    - family: Josefin Sans
      fonts:
        - asset: fonts/josefin_sans/JosefinSans-Bold.ttf
          weight: 700
        - asset: fonts/josefin_sans/JosefinSans-SemiBold.ttf
          weight: 600
        - asset: fonts/josefin_sans/JosefinSans-Light.ttf
          weight: 300
        - asset: fonts/josefin_sans/JosefinSans-Regular.ttf
          #weight: 400

  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
